apiVersion: v1
kind: Pod
metadata:
  name: busybox-echo
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo 'The BEST DevOps COURSE!!!' && sleep 3600"]
