apiVersion: v1
kind: Service
metadata:
  name: final-exam
  namespace: zafar
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
