apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-something
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-something
  template:
    metadata:
      labels:
        app: frontend-something
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - node2
      containers:
      - name: something
        image: nvrbckdown/something
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
